### ISSUE TITLE
Hatalı Dönüştürme işlemi

### ISSUE THREAD

**Issue by mesuutt** [meacer/deasciifier#7]
`Tasci` kelimesi `Taşçı` olarak çevrilmesi lazımken `Taşçi` olarak çevriliyor.

**Comment by meacer** [comment]
4 sene sonra merhaba :) Bu kelime artık doğru şekilde düzeltiliyor ancak tam olarak ne zaman düzeldiğini hatırlamıyorum.

**Comment by mesuutt** [comment]
Selam kardesim 👋
4 sene sonra olsa da problem yok, bunu gorunce gecmisi hatirladim 😄  Donus icin tesekkurler ♥️
