### ISSUE TITLE
Firefox eklentisi

### ISSUE THREAD

**Issue by YavuzSelimGugen** [meacer/deasciifier#9]
Eklentinin Firefox sayfasina ulaşılamıyor.

**Comment by meacer** [comment]
Selam, Firefox eklentisi bana ait değil. https://twitter.com/emresevinc'ten güncellenmesini isteyebilirsiniz.

**Comment by meacer** [comment]
Tekrar selam, yeni Firefox eklentisini şuraya yükledim: https://addons.mozilla.org/en-US/firefox/addon/deasciifier/

**Comment by YavuzSelimGugen** [comment]
> 
> 
> Tekrar selam, yeni Firefox eklentisini şuraya yükledim: https://addons.mozilla.org/en-US/firefox/addon/deasciifier/

Çok teşekkürler
